name: 'Notify old PRs'
description: 'A Github action that notifies old PRs that are open longer than 2 days'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'orange'
