name: Check for Vulnerabilities
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
    branches:
      - main

jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.19.0"

      - name: Run Snyk Security Scanner
        uses: movingimage-evp/github-actions/security/setup@16bba8ec334efd739346a75c781aabb958862078 # main
        with:
          github-packages-token: ${{ secrets.PACKAGES_MI_MAVEN_REPOSITORY_ACCESS_TOKEN }}
          snyk-token: ${{ secrets.SNYK_API_KEY }}
          code-severity-threshold: "medium"
          test-severity-threshold: "critical"
